environment: prod
frontendDomain: games.jeffreycarr.dev
port: 8080
fullCertPath: "/etc/letsencrypt/live/web-games.backend.jeffreycarr.dev/fullchain.pem"
privateKeyPath: "/etc/letsencrypt/live/web-games.backend.jeffreycarr.dev/privkey.pem"